name: all_packages
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: bluefireteam/melos-action@v2
      - name: "Analyze"
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: true
          fatal-warnings: true

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: bluefireteam/melos-action@v2
      - name: "Check formatting"
        run: melos run format-check

  test_linux:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: bluefireteam/melos-action@v2
        with:
          melos-version: '3.0.0-dev.0'   
      - name: "Install Firebase CLI"
        run: |
          sudo npm i -g firebase-tools
      - name: Install FlutterFire
        run: |
          dart pub global activate --source="path" . --executable="flutterfire" --overwrite  
      - name: "Run Tests"
        run: melos run test --no-select

  test_macos:
    runs-on: macos-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: bluefireteam/melos-action@v2
        with:
          melos-version: '3.0.0-dev.0'
      - name: "Install Firebase CLI"
        run: |
          sudo npm i -g firebase-tools 
      - name: Login to Firebase CLI
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > service_account.json
          firebase login:ci --token "$(firebase use --token --project flutterfire-cli-test-f6f57 --service-account service_account.json)"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      - name: Install FlutterFire
        run: |
          dart pub global activate --source="path" . --executable="flutterfire" --overwrite        
      - name: "Run Tests"
        run: melos run test --no-select

  test_windows:
    runs-on: windows-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: bluefireteam/melos-action@v2
        with:
          melos-version: '3.0.0-dev.0'  
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        name: Install Node.js 16
        with:
          node-version: "16"       
      - name: "Install Firebase CLI"
        run: |
          sudo npm i -g firebase-tools
      - shell: bash
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase login --no-localhost   
      - name: Install FlutterFire
        run: |
          dart pub global activate --source="path" . --executable="flutterfire" --overwrite        
      - uses: actions/checkout@v2
      - name: "Run Tests"
        run: cmd /K melos run test --no-select
